### ISSUE TITLE
Cant see trophies

### ISSUE THREAD

**Issue by EmpressPotato** [GizmoTheMoonPig/OpenBlocksTrophies#16] opened 2023-10-19 03:54 UTC
### Mod Version

Direwolf 1.20

### Bug Description

i place the trophies and I cant see them at all but my husband can see them we are in the same server

### Steps to Reproduce

got trophy
placed trophy
invisible
![2023-10-18](https://github.com/GizmoTheMoonPig/OpenBlocksTrophies/assets/148413186/79165fca-87c6-4815-aca8-c476f961c89a)

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment] 2023-10-19 04:01
Can you send me your latest.log file? Looks like trophies aren't properly syncing to your client

**Comment by EmpressPotato** [comment] 2023-10-19 04:42
[2023-10-18-1.log.gz](https://github.com/GizmoTheMoonPig/OpenBlocksTrophies/files/13037988/2023-10-18-1.log.gz)
[2023-10-18-2.log.gz](https://github.com/GizmoTheMoonPig/OpenBlocksTrophies/files/13037990/2023-10-18-2.log.gz)

**Comment by EmpressPotato** [comment] 2023-10-19 04:45
[latest.log](https://github.com/GizmoTheMoonPig/OpenBlocksTrophies/files/13038003/latest.log)

**Comment by GizmoTheMoonPig** [comment] 2023-10-19 18:07
this log is incomplete, its missing the whole first part of it

**Comment by EmpressPotato** [comment] 2023-10-19 20:58
that is all that was in my log that I sent you

**Comment by EmpressPotato** [comment] 2023-10-20 01:57
here is a new log 
[latest.log](https://github.com/GizmoTheMoonPig/OpenBlocksTrophies/files/13049209/latest.log)

**Comment by GizmoTheMoonPig** [comment] 2023-10-22 17:56
I just uploaded a new version of the mod that might fix it? I added some additional debug lines so I can see whats going on as well. Try out 3.1 (https://www.curseforge.com/minecraft/mc-mods/openblocks-trophies/files/4811484) and let me know if it fixes stuff. If not send me the debug.log this time as that will contain more useful info for me

**Comment by EmpressPotato** [comment] 2023-10-26 03:24
I can see them now, they are no longer a obsidian base

**Comment by EmpressPotato** [comment] 2023-10-26 03:24
Thank you so much! :)

**Comment by GizmoTheMoonPig** [comment] 2023-10-27 14:33
Glad it's working now :)
Curious, we're you playing on a LAN server? That may have been why I wasn't able to reproduce this. Gonna close it regardless since it's solved but feel free to let me know

**Closed as completed by GizmoTheMoonPig** 2023-10-27 14:33 UTC
Labels: bug

**Comment by EmpressPotato** [comment] 2023-10-28 01:41
Yes I was on a LAN server i was playing on my husbands server with him
